# Generated by Django 4.0.4 on 2022-06-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('barcode', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=500)),
                ('perishable', models.BooleanField(default=False)),
                ('weight', models.FloatField(default=0)),
            ],
        ),
    ]
